### ISSUE TITLE
New Response for Z21ActionGetSerialNumber()

### ISSUE THREAD

**Issue by littleyoda** [grizeldi/z21-drive#2]
I'm testing the Z21ActionGetSerialNumber() Request, but I didn't  get a response with the serial number from the z21

The Class for Testing:
https://github.com/littleyoda/z21-drive/blob/main/src/z21Drive/testing/Serialnumber.java

**Comment by grizeldi** [comment]
Will look into it. Serial number request was one of those things which I implemented because why not and never really tested it.

**Comment by littleyoda** [comment]
I found the error:

In ActionGetSerialNumber you are currently sending
        byteRepresentation.add((byte) 0x00);
        byteRepresentation.add((byte) 0x10);

Correct would be 
        byteRepresentation.add((byte) 0x10);
        byteRepresentation.add((byte) 0x00);

**Comment by grizeldi** [comment]
I just fixed the way ypu said it should be. But I can't test right now, because I'm on mobile.
Could you please test it and tell me if it works?

**Comment by littleyoda** [comment]
Works fine. Thanks.

**Comment by grizeldi** [comment]
Ok, great ;)
