### ISSUE TITLE
Loco Adresses are limited to 63

### ISSUE THREAD

**Issue by littleyoda** [grizeldi/z21-drive#3]
Currently the Loco Addresses are limited to 63.

DCC supports even with short numbers 127 Addresses. With long addresses more than 10.000.

According to the protocol, the  z21 supports Addresses with a length of 14 bits.

**Comment by grizeldi** [comment]
Hmm... I'll try to add some bit shift magic to support even bigger adresses.

**Comment by littleyoda** [comment]
If you have any problems, don't  hesitate to contact me.
http://www.open4me.de/index.php/impressum/

**Comment by grizeldi** [comment]
Sorry for not fixing it yet, but today I took some time and moved everything to gradle, so now we have travis builds and also easier build process. Took me quite some time to tell Intellij Idea and git to get along with the new project structure.

**Comment by grizeldi** [comment]
Fixed this issue in the GetLocoInfo action. Stumbled upon some very old and weird code that I honestly had no clue what was going on. Replaced it with some simple bit shifting and now it works.
I have written that code when I still didn't know about bit operations and result was, ... well... weird.
I'll fix the issue in the other classes in the following days.

**Comment by littleyoda** [comment]
thx

**Comment by littleyoda** [comment]
Can you send me an e-mail?
sb-www0703-xuzwshf74k8qzgyg@bursch.com

**Comment by grizeldi** [comment]
All actions should now support extended addresses. I'm low on time so I couldn't test it. If you have some time to spare I would be glad if you could test it (commits 90e9f1c0ca945f561aa36d8c63113b00f4de59fb and ff4b729fd005ffd233238cd59f2c036d9db4be8f).

**Comment by littleyoda** [comment]
I will test it.

You removed the Z21ActionLanXCVPomReadByte class!?

**Comment by grizeldi** [comment]
Ok cool.
I removed it by mistake and just figured it out. When pushing I thought
that the deleted item was some old class which I renamed but git had
problems detecting.
I'll revert the commits tomorrow and re push the actual changes. Please
test anyway, but you'll have to temporary delete the pomread test.

**Comment by littleyoda** [comment]
I tested it and it  works fine for me.

**Comment by grizeldi** [comment]
Okay awesome. My internet was down for the most of the day, so I couldn't revert the failed commit.
I'll try tomorrow if my internet will be up.
(Writing this on mobile data)

**Comment by grizeldi** [comment]
So now everything supports using extended addresses.
